### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by uDEV2019**
Complete german translation, except for plugin-section

For sure it is translateable in the JSON files, but for now as german only and not multilanguage in one JSON for all languages

But, there is a mistake in source string "_adsFinishSetupAds_desc"
_adsFinishSetupAds_desc = This feature will disable ads in File Explorer.
_adsFileExplorerAds_desc = This feature will disable ads in File Explorer.

I did a translation that should reflect the right option.

### CODE REVIEW

**Comment by uDEV2019** [comment]
Added the existing Plugins with german translation to a new directory.

toolDebloater.json will follow later

**Comment by uDEV2019** [comment]
@Belim Ich würde grundsätzlich empfehlen für die Diskussion rundum die Plugins bei Englisch zu bleiben.

Suggestion:
You create a respository and name it "xd-AntiSpy-plugins", where you create for now a folder "en-US" or just "en" where you put in the default plugins that you deliver with your xd-AntiSpy releases.
The Community then contribute new plugins into the "en" folder or if the plugin is in the native language of the contributer, e.g. german, then with the pull request there get more folders like "de-DE"/"de" or "ru-RU"/"ru" and so on created.

In xd-AntiSpy you point the Option "more plugins" to that plugin-repository.
Everyone then can choose by own what plugins in which language he/she want to use.

**Comment by Belim** [comment]
Love the idea of a separate xd-AntiSpy repo or branch

**Comment by uDEV2019** [comment]
@Belim As i can see you updated the release links with the new translation.
I think there went something wrong when building the xd-AntiSpy.resources.dll.
The String "menu_toolsToolStripMenuItem" is not the same as i did it in translation.
The Word "Tools" must be "Werkzeuge" and not "Spezial". 
"Spezial" is the machine-translated thing from your first v4.0.6 release.

**Comment by Belim** [comment]
I addressed that here https://github.com/builtbybel/xd-AntiSpy/pull/14#issuecomment-2222441005

**Pull request merged**
